name: master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  develop:
    runs-on: ubuntu-latest
    container:
      image: jsdecena/php74-composer
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit tests/
